version: 2.1

jobs:
  frontend-build-and-push:
    docker:
      - image: cimg/node:18.18.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build frontend
          command: npm run build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image (Frontend with Nginx)
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t "$DOCKERHUB_USERNAME/frontend:$TAG" -f Dockerfile.nginx .
      - run:
          name: Push Docker image (Frontend)
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/frontend:$TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - frontend-build-and-push